### ISSUE TITLE
1.19.4 version reads as 1.19.3

### ISSUE THREAD

**Issue by PyroEighteen** [CammiePone/Icarus#100]
I installed the 1.19.4 version just fine as it read it as what it is, but upon loading minecraft it gives me an error saying "icarus 1.15 needs 1.19.3". This is the only wings mod I could find that is both fabric and has 1.19.4 as an option, please fix this :(

**Comment by UpcraftLP** [comment]
Whoops, my bad. I accidentally tagged it as 1.19.4 when it is actually 1.19.3.

that said you can likely still make it work on 1.19.4 by setting up [dependency overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides)

**Comment by PyroEighteen** [comment]
> Whoops, my bad. I accidentally tagged it as 1.19.4 when it is actually 1.19.3.
> 
> that said you can likely still make it work on 1.19.4 by setting up [dependency overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides)

I'm not entirely sure how to do that. It seems like I can just use the Visual Studio Code app, however I'm unsure of which coding language to use, nor how to apply it to the config file. It's likely easier than I think it is but I have never messed around with code.

**Comment by PyroEighteen** [comment]
> > Whoops, my bad. I accidentally tagged it as 1.19.4 when it is actually 1.19.3.
> > that said you can likely still make it work on 1.19.4 by setting up [dependency overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides)
> 
> I'm not entirely sure how to do that. It seems like I can just use the Visual Studio Code app, however I'm unsure of which coding language to use, nor how to apply it to the config file. It's likely easier than I think it is but I have never messed around with code.

Yeah it doesn't work at all when I go by the information in the link you gave me. I've tried it exactly as shown. 

{
  "version": 1,
  "overrides": {
    "icarus-1.15": {
      "+depends": {
        "minecraft": "1.19.x"
      }
    }
  }
}

**Comment by UpcraftLP** [comment]
the mod id is `icarus`, not `icarus-1.15`. and you most likely want to *remove* the version dependency, not add one.

**Comment by CryoNine** [comment]
> the mod id is `icarus`, not `icarus-1.15`. and you most likely want to _remove_ the version dependency, not add one.

Do I add the code as a text file?

**Comment by UpcraftLP** [comment]
what code?

yes, the dependency override config is a text file

**Comment by PyroEighteen** [comment]
> what code?
> 
> yes, the dependency override config is a text file

I tried to do the code that ignores dependency but it only comes up with this error

Error parsing dependency overrides!
net.fabricmc.loader.impl.FormattedException: Failed to parse C:\Users\ethan\curseforge\minecraft\Instances\La Preferible\config\fabric_loader_dependencies.json
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:59)
	at net.fabricmc.loader.impl.metadata.DependencyOverrides.<init>(DependencyOverrides.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:205)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.nio.file.AccessDeniedException: C:\Users\ethan\curseforge\minecraft\Instances\La Preferible\config\fabric_loader_dependencies.json
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at net.fabricmc.loader.impl.metadata.DependencyOverrides.<init>(DependencyOverrides.java:53)
	... 5 more


The code I tried is

{
  "version": 1,
  "overrides": {
    "specificmod": {
      "-depends": {
        "minecraft": "IGNORED"
      }
    }
  }
}

**Comment by UpcraftLP** [comment]
`Caused by: java.nio.file.AccessDeniedException: C:\Users\ethan\curseforge\minecraft\Instances\La Preferible\config\fabric_loader_dependencies.json`

this seems to be an issue with some process on your system keeping a lock on the file? or a permissions issue?

**Comment by CryoNine** [comment]
> `Caused by: java.nio.file.AccessDeniedException: C:\Users\ethan\curseforge\minecraft\Instances\La Preferible\config\fabric_loader_dependencies.json`
> 
> this seems to be an issue with some process on your system keeping a lock on the file? or a permissions issue?

Hm. If it's a permissions issue, for whatever reason on my main pc admin privileges can't be turned on completely (I've tried everything I could find online) however I do have more than one computer and on all of them admin does work so what I can do is port the files to one of those, try the code, then port it to my main pc. I'll try that over the weekend.

Also this is my alt, if you are confused. Probably pretty obvious though because Pyro/Cryo lmao.
