### ISSUE TITLE
Ticking Player error (Loading IcarusClient on Server causing RuntimeException)

### ISSUE THREAD

**Issue by Skullians** [CammiePone/Icarus#112]
Hey, using 1.19.2 Fabric Icarus 1.14.
Neruina (ticking entity / player fixer) is kicking players with the Ticking player error because the server is trying to load the IcarusClient class on the server side.

Can a fix be pushed for this for 1.19.2?

```log
net.minecraft.class_148: Ticking player
	at net.minecraft.class_3222.method_14226(class_3222.java:551)
	at net.minecraft.class_3244.mixinextras$bridge$method_14226$259(class_3244.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickPlayer(TickHandler.java:122)
	at net.minecraft.class_3244.wrapOperation$eoe000$neruina$catchTickingPlayer$notTheCauseOfTickLag(class_3244.java:11515)
	at net.minecraft.class_3244.method_18784(class_3244.java:268)
	at net.minecraft.class_2535.method_10754(class_2535.java:248)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Cannot load class dev.cammiescorner.icarus.client.IcarusClient in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at dev.cammiescorner.icarus.core.util.IcarusHelper.applySpeed(IcarusHelper.java:58)
	at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:57)
	at net.minecraft.class_1661.md9a3f02$trinkets$lambda$updateItems$0$3(class_1661.java:8193)
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362)
	at net.minecraft.class_1661.md9a3f02$trinkets$lambda$updateItems$1$2(class_1661.java:8192)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1661.handler$hao001$trinkets$updateItems(class_1661.java:8191)
	at net.minecraft.class_1661.method_7381(class_1661.java:259)
	at net.minecraft.class_1657.method_6007(class_1657.java:567)
	at net.minecraft.class_1309.method_5773(class_1309.java:2385)
	at net.minecraft.class_1657.method_5773(class_1657.java:284)
	at net.minecraft.class_3222.method_14226(class_3222.java:487)
	... 12 more
```

**Comment by UpcraftLP** [comment]
fixed in v1.14.1
