### ISSUE TITLE
Internal server error kicking player

### ISSUE THREAD

**Issue by Aaron995** [CammiePone/Icarus#13]
Hello I have players getting kicked after trying to fly with their wings leaving a flying mount. 

```
06.01 14:56:48 [Server] Server thread/WARN Failed to handle packet for /
06.01 14:56:48 [Server] INFO net.minecraft.class_148: Ticking player
06.01 14:56:48 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:543) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_3244.method_18784(class_3244.java:213) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_2535.method_10754(class_2535.java:238) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
06.01 14:56:48 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking in environment type SERVER
06.01 14:56:48 [Server] INFO at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.12.jar:?]
06.01 14:56:48 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.12.12.jar:?]
06.01 14:56:48 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.12.12.jar:?]
06.01 14:56:48 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
06.01 14:56:48 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
06.01 14:56:48 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
06.01 14:56:48 [Server] INFO at net.fabricmc.fabric.impl.networking.ClientSidePacketRegistryImpl.toPacket(ClientSidePacketRegistryImpl.java:56) ~[fabric-networking-v0-0.3.5+b4f4f6cd65-a521e3865ef1d5c4.jar:?]
06.01 14:56:48 [Server] INFO at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:70) ~[fabric-networking-v0-0.3.5+b4f4f6cd65-a521e3865ef1d5c4.jar:?]
06.01 14:56:48 [Server] INFO at net.fabricmc.fabric.api.network.ClientSidePacketRegistry.sendToServer(ClientSidePacketRegistry.java:89) ~[fabric-networking-v0-0.3.5+b4f4f6cd65-a521e3865ef1d5c4.jar:?]
06.01 14:56:48 [Server] INFO at dev.cammiescorner.icarus.core.network.client.DeleteHungerMessage.send(DeleteHungerMessage.java:30) ~[icarus-1.9.jar:?]
06.01 14:56:48 [Server] INFO at dev.cammiescorner.icarus.core.util.IcarusHelper.applySpeed(IcarusHelper.java:63) ~[icarus-1.9.jar:?]
06.01 14:56:48 [Server] INFO at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:56) ~[icarus-1.9.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_1661.mdca9516$lambda$updateItems$0$1(class_1661.java:1700) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:335) ~[trinkets-3.1.0.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_1661.mdca9516$lambda$updateItems$1$0(class_1661.java:1699) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_1661.handler$dca001$updateItems(class_1661.java:1698) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_1661.method_7381(class_1661.java:266) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_1657.method_6007(class_1657.java:556) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_1309.method_5773(class_1309.java:2349) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_1657.method_5773(class_1657.java:274) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO at net.minecraft.class_3222.method_14226(class_3222.java:479) ~[server-intermediary.jar:?]
06.01 14:56:48 [Server] INFO ... 9 more
```

This is the error generating in the server console.

**Comment by CammiePone** [comment]
Probably don't wanna include the user's IP address in the log. As for the crash, I'll take a look into it. What mount is being used?

**Comment by Aaron995** [comment]
Oops copied the wrong thing, this error was mostly done by falling off the AdventureZ dragon.

**Comment by CammiePone** [comment]
Have you tried it with Mythic Mounts? 'Cause that could be an AdventureZ issue. A lot of the -Z mods tend to cause crashes with other mods when they shouldn't

**Comment by Aaron995** [comment]
Nope this pack only has the dragon currently, will file a bug report with them if it's their issue then :)

**Comment by CammiePone** [comment]
Give it a go with Mythic Mounts first and see if it's reproduceable on other mounts. Also probably test horses, minecarts, boats, etc.

If it is, then it almost definitely is on my end, but I don't see how getting off of a mount would cause the packet to be loaded on the wrong side...

**Comment by Aaron995** [comment]
Same error when trying to fly after dismounting a boat that is falling

**Comment by Aaron995** [comment]
https://streamable.com/r14fki

**Comment by CammiePone** [comment]
Interesting. Time to suffer in figuring that out then.

May be using a deprecated API which could be it. I'll try and fix it tonight.
