### ISSUE TITLE
some kind of error with inmis

### ISSUE THREAD

**Issue by ImUrX** [CammiePone/Icarus#3]
this doesnt crash but its kind of bothering
```[20:48:48] [Server thread/FATAL]: Error executing task on Server
java.lang.ClassCastException: class draylar.inmis.item.BackpackItem cannot be cast to class dev.cammiescorner.icarus.common.items.WingItem (draylar.inmis.item.BackpackItem and dev.cammiescorner.icarus.common.items.WingItem are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @6c284af)
        at dev.cammiescorner.icarus.core.network.client.DeleteHungerMessage.lambda$handle$1(DeleteHungerMessage.java:41) ~[icarus-1.4.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.cammiescorner.icarus.core.network.client.DeleteHungerMessage.lambda$handle$2(DeleteHungerMessage.java:39) ~[icarus-1.4.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at dev.cammiescorner.icarus.core.network.client.DeleteHungerMessage.lambda$handle$3(DeleteHungerMessage.java:39) ~[icarus-1.4.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bom000$modifiedRunLoop(MinecraftServer.java:9899) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by CammiePone** [comment]
yknow I forgot to check that whoopsie

**Comment by CammiePone** [comment]
okay now I can close it

**Comment by CammiePone** [comment]
You can get the file from Modrinth or here, because CurseForge is being a butt and not letting me upload rn

**Comment by ImUrX** [comment]
alright, thanks :P
