### ISSUE TITLE
[bug] exiting create contraption at speed causes player kick

### ISSUE THREAD

**Issue by Merith-TK** [CammiePone/Icarus#63]
```
[04:20:03] [Server thread/WARN]: Failed to handle packet for /<redacted IP>
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Cannot load class dev.cammiescorner.icarus.client.IcarusClient in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at dev.cammiescorner.icarus.core.util.IcarusHelper.applySpeed(IcarusHelper.java:58) ~[icarus-1.14.jar:?]
        at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:57) ~[icarus-1.14.jar:?]
        at net.minecraft.class_1661.md0d041f$trinkets$lambda$updateItems$0$3(class_1661.java:3193) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.4.2.jar:?]
        at net.minecraft.class_1661.md0d041f$trinkets$lambda$updateItems$1$2(class_1661.java:3192) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1661.handler$dbh001$trinkets$updateItems(class_1661.java:3191) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:567) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
        ... 9 more
[04:20:04] [Server thread/INFO]: Cryodine lost connection: Internal server error
```

**Comment by suerion** [comment]
Here the same 

```
[13:25:36] [Server thread/WARN] (class_3242) Failed to handle packet for /xxxxxxx:64675
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:551) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Cannot load class dev.cammiescorner.icarus.client.IcarusClient in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at dev.cammiescorner.icarus.core.util.IcarusHelper.applySpeed(IcarusHelper.java:58) ~[icarus-1.14.jar:?]
        at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:57) ~[icarus-1.14.jar:?]
        at net.minecraft.class_1661.mdc60ca3$trinkets$lambda$updateItems$0$2(class_1661.java:3193) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.4.2.jar:?]
        at net.minecraft.class_1661.mdc60ca3$trinkets$lambda$updateItems$1$1(class_1661.java:3192) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1661.handler$elp001$trinkets$updateItems(class_1661.java:3191) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:567) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2385) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:487) ~[server-intermediary.jar:?]
        ... 9 more
[13:25:36] [Server thread/INFO] (class_3244) Suerion lost connection: Internal server error
[13:25:36] [Server thread/INFO] (MinecraftServer) Suerion left the game
```

**Comment by Seceroth** [comment]
This is still happening on Fabric 1.20.1, Icarus v1.16.

**Comment by UpcraftLP** [comment]
Hey, could you test whether this still happens in the latest 1.20.1 version of the mod?

I've rewritten a lot of the internals so am not sure whether it has been fixed in the process of that, or whether it needs some more attention.

**Comment by UpcraftLP** [comment]
Closing this for now, if it still appears on 1.20.1+ feel free to make a new issue.
