### ISSUE TITLE
The server kicked out the player abnormally

### ISSUE THREAD

**Issue by konsheng** [CammiePone/Icarus#78]
[19:45:50] [Server thread/WARN]: Failed to handle packet for /114.86.79.16:28633
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bfi000$carpet$modifiedRunLoop(MinecraftServer.java:21942) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.RuntimeException: Cannot load class dev.cammiescorner.icarus.client.IcarusClient in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at dev.cammiescorner.icarus.core.util.IcarusHelper.applySpeed(IcarusHelper.java:45) ~[【伊卡洛斯之翼】icarus-1.16.jar:?]
        at dev.cammiescorner.icarus.common.items.WingItem.tick(WingItem.java:51) ~[【伊卡洛斯之翼】icarus-1.16.jar:?]
        at net.minecraft.class_1661.mdda6eda$trinkets$lambda$updateItems$0$2(class_1661.java:3693) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[【MOD前置 】trinkets-3.7.1.jar:?]
        at net.minecraft.class_1661.mdda6eda$trinkets$lambda$updateItems$1$1(class_1661.java:3692) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1661.handler$hlp001$trinkets$updateItems(class_1661.java:3691) ~[server-intermediary.jar:?]
        at net.minecraft.class_1661.method_7381(class_1661.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_6007(class_1657.java:568) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2419) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 10 more

**Comment by CammiePone** [comment]
try running it without Carpet

**Comment by konsheng** [comment]
> 尝试在没有地毯的情况下运行它

Is there any way to solve the problems caused by Carpet and this mod?

**Comment by UpcraftLP** [comment]
Should be fixed in the next release.
