### ISSUE TITLE
Networking crash upon loading into singleplayer world.

### ISSUE THREAD

**Issue by Hyxth** [CammiePone/Icarus#96]
[latest.log](https://github.com/Up-Mods/Icarus/files/15304753/latest.log)
Networking mumbo jumbo error that I do not understand at all and would like your input upon. 
Error when loading into world:
![111](https://github.com/Up-Mods/Icarus/assets/127713838/daa625b2-a239-44d7-8d99-eb09a01598ed)
This occurs when this mod is present within the extensive modpack that i have created, and when i use it by itself.

Logs for the instance in which i only had icarus and it's required dependencies installed:[latest.log](https://github.com/Up-Mods/Icarus/files/15305774/latest.log)

**Comment by A5ho9999** [comment]
I get same error using 2.8.1+Fabric
```
[20:41:38] [Netty Local Client IO #0/ERROR]: Encountered exception while handling in channel with name "icarus:sync_config_values"
java.lang.IndexOutOfBoundsException: readerIndex(11) + length(4) exceeds writerIndex(11): UnpooledSlicedByteBuf(ridx: 11, widx: 11, cap: 11/11, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 11, cap: 11))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.82.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809) ~[netty-buffer-4.1.82.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readFloat(AbstractByteBuf.java:856) ~[netty-buffer-4.1.82.Final.jar:?]
	at net.minecraft.network.PacketByteBuf.readFloat(PacketByteBuf.java:1388) ~[client-intermediary.jar:?]
	at dev.cammiescorner.icarus.network.s2c.SyncConfigValuesPacket.decode(SyncConfigValuesPacket.java:35) ~[Icarus-Fabric-2.8.1.jar:?]
	at commonnetwork.networking.FabricNetworkHandler.lambda$registerPacket$1(FabricNetworkHandler.java:39) ~[common-networking-fabric-1.0.3-1.20.1.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$dnp000$fabric-networking-api-v1$handleCustomPayload(ClientPlayNetworkHandler.java:3268) ~[client-intermediary.jar:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onCustomPayload(ClientPlayNetworkHandler.java) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.network.packet.s2c.play.CustomPayloadS2CPacket.apply(CustomPayloadS2CPacket.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.handlePacket(ClientConnection.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.channelRead0(ClientConnection.java:52) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:686) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:671) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$000(LocalChannel.java:50) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel$1.run(LocalChannel.java:68) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by unilock** [comment]
I think this is because `SyncConfigValuesPacket#encode` doesn't write the `requiredFoodAmount` config value, which is probably just an oversight.

https://github.com/Up-Mods/Icarus/blob/0a28f2418c63a14978db845a5300cfc7e392edb9/Common/src/main/java/dev/cammiescorner/icarus/network/s2c/SyncConfigValuesPacket.java#L17-L22

Adding `buf.writeFloat(requiredFoodAmount());` to the end would probably fix the issue!

**Comment by CammiePone** [comment]
oh the woes of updating a mod while tired
